### ISSUE TITLE
Uncaught Error: Could not find file

### ISSUE THREAD

**Issue by tmm1** [russpowers/nim-atom#1]
Getting this error even though I have the file open in the editor and I see it on my filesystem.

**Atom Version**: 1.0.15
**System**: Mac OS X 10.11
**Thrown From**: [nim](https://github.com/russpowers/nim-atom) package, v0.2.9

### Stack Trace

Uncaught Error: Could not find file /Users/tmm1/code/learn-nim/ffmpeg.nim

```
At /Users/tmm1/.atom/packages/nim/lib/known-files.coffee:32

Error: Could not find file /Users/tmm1/code/learn-nim/ffmpeg.nim
  at findFile (/Users/tmm1/.atom/packages/nim/lib/known-files.coffee:32:17)
  at Object.module.exports.getCanonical (/Users/tmm1/.atom/packages/nim/lib/known-files.coffee:41:14)
  at Executor.parseDefinition (/Users/tmm1/.atom/packages/nim/lib/executor.coffee:50:24)
  at OnDemandCaas.currentCb (/Users/tmm1/.atom/packages/nim/lib/executor.coffee:72:13)
  at OnDemandCaas.Caas.onCommandDone (/Users/tmm1/.atom/packages/nim/lib/caas.coffee:43:6)
  at process.BufferedProcess.exit (/Users/tmm1/.atom/packages/nim/lib/on-demand-caas.coffee:27:10)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:467:12)

```

### Commands

```
     -0:25 symbols-view:toggle-file-symbols (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:24.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:24.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:22.7.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:22 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:22 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:21.6.0 pane:show-item-1 (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:21.1.0 symbols-view:toggle-file-symbols (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:20.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:20.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:10.5.0 core:close (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:10 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:08.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.6.0 go-to-line:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:04.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -0:01.5.0 nim:goto-definition (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "terminal",
      "git-plus",
      "atomatigit",
      "term2",
      "language-nim"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "nim": {
    "nimExecutablePath": "/usr/local/bin/nim",
    "onTheFlyChecking": true,
    "nimsuggestEnabled": true,
    "nimsuggestExecutablePath": "~/.nimble/bin/nimsuggest"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.8.7
autocomplete-emojis, v2.2.2
color-picker, v2.0.12
git, v0.0.0
go-plus, v3.5.1
language-puppet, v0.14.0
language-rust, v0.4.5
linter, v1.6.0
linter-rust, v0.2.9
minimap, v4.13.3
minimap-git-diff, v4.1.8
minimap-hide, v0.3.0
nim, v0.2.9
racer, v0.17.2
remote-atom, v1.2.7
rust-api-docs-helper, v0.5.1
vim-mode, v0.60.0

# Dev
No dev packages
```

**Comment by russpowers** [comment]
On Windows, Nim reports paths as lowercase, but it looks like that is different on OS X.  I will get this fixed.

**Comment by russpowers** [comment]
FYI you will need to restart Atom after updating the package.

**Comment by tmm1** [comment]
Thanks, it works now!
