### ISSUE TITLE
Uncaught ReferenceError: folderPath is not defined

### ISSUE THREAD

**Issue by hvze** [russpowers/nim-atom#16]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.12.5
**Electron Version**: 1.3.9
**System**: Mac OS X 10.12
**Thrown From**: [nim](https://github.com/russpowers/nim-atom) package, v0.3.6

### Stack Trace

Uncaught ReferenceError: folderPath is not defined

```
At /Users/haze/.atom/packages/nim/lib/nimble-info.coffee:32

ReferenceError: folderPath is not defined
    at new NimbleInfo (/Users/haze/.atom/packages/nim/lib/nimble-info.coffee:32:46)
    at Project.detectInfo (/Users/haze/.atom/packages/nim/lib/project.coffee:54:25)
    at new Project (/Users/haze/.atom/packages/nim/lib/project.coffee:47:6)
    at /Users/haze/.atom/packages/nim/lib/project-manager.coffee:34:11
    at ProjectManager.update (/Users/haze/.atom/packages/nim/lib/project-manager.coffee:33:17)
    at Object.updateProjectManager (/Users/haze/.atom/packages/nim/lib/nim.coffee:66:21)
    at /Users/haze/.atom/packages/nim/lib/nim.coffee:269:10
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Project.module.exports.Project.addPath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:270:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:985:40
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/application-delegate.js:27:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
```

### Commands

```
  2x -0:09.6.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
  4x -0:08.7.0 tree-view:toggle (atom-text-editor.editor.is-focused)
  4x -0:07.4.0 key-binding-resolver:toggle (atom-text-editor.editor.is-focused)
     -0:05.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:02.7.0 application:add-project-folder (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-ocaml",
      "linter-ocaml",
      "language-perl"
    ],
    "telemetryConsent": "no",
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  },
  "nim": {
    "nimsuggestEnabled": true,
    "onTheFlyChecking": true
  }
}
```

### Installed Packages

```coffee
# User
atom-format-lua, v0.1.5 (inactive)
atom-htmltidy, v5.1.0 (active)
atom-perl6-editor-tools, v0.9.18 (active)
autoclose-html, v0.23.0 (active)
build, v0.67.0 (active)
busy, v0.7.0 (active)
felix_speedtest, vundefined (active)
Glacier-Green-ui, v0.5.0 (inactive)
greti-syntax, v0.6.0 (inactive)
haskell-hoogle, v0.1.3 (inactive)
hyperclick, v0.0.39 (active)
isotope-ui, v2.7.1 (inactive)
language-felix, v0.0.8 (active)
language-haskell, v1.10.1 (active)
language-lua, v0.9.11 (active)
language-ocaml, v1.1.2 (inactive)
language-perl6fe, v1.7.3 (active)
language-rust, v0.4.8 (active)
line-count, v0.5.0 (inactive)
linter, v1.11.18 (active)
linter-ocaml, v1.2.0 (inactive)
linter-rust, v0.7.1 (active)
nim, v0.3.6 (active)
ocaml-indent, v0.4.0 (inactive)
ocaml-merlin, v0.9.4 (inactive)
racer, v0.20.0 (active)
refactor, v0.11.1 (active)
rustfmt, v0.1.3 (active)
script, v3.11.1 (inactive)
webbox-color, v0.5.9 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.45.0 (inactive)
base16-tomorrow-dark-theme, v1.3.0 (inactive)
base16-tomorrow-light-theme, v1.3.0 (inactive)
one-dark-ui, v1.6.2 (inactive)
one-light-ui, v1.6.2 (active)
one-dark-syntax, v1.5.0 (inactive)
one-light-syntax, v1.5.0 (active)
solarized-dark-syntax, v1.0.5 (inactive)
solarized-light-syntax, v1.0.5 (inactive)
about, v1.7.0 (active)
archive-view, v0.62.0 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.13.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.4 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.42.0 (active)
bracket-matcher, v0.82.2 (active)
command-palette, v0.39.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.40.0 (active)
find-and-replace, v0.202.2 (inactive)
fuzzy-finder, v1.4.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.2 (active)
image-view, v0.60.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.2 (inactive)
markdown-preview, v0.158.8 (active)
metrics, v1.1.2 (active)
notifications, v0.65.1 (active)
open-on-github, v1.2.1 (inactive)
package-generator, v1.0.1 (inactive)
settings-view, v0.243.1 (active)
snippets, v1.0.4 (active)
spell-check, v0.68.4 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.2 (active)
symbols-view, v0.113.1 (inactive)
tabs, v0.103.0 (active)
timecop, v0.33.2 (active)
tree-view, v0.210.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.35.1 (active)
whitespace, v0.35.0 (active)
wrap-guide, v0.38.2 (active)
language-c, v0.54.0 (active)
language-clojure, v0.22.1 (active)
language-coffee-script, v0.48.0 (active)
language-csharp, v0.13.0 (active)
language-css, v0.40.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.43.0 (active)
language-html, v0.47.1 (active)
language-hyperlink, v0.16.1 (active)
language-java, v0.24.0 (active)
language-javascript, v0.122.0 (active)
language-json, v0.18.3 (active)
language-less, v0.29.6 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.37.0 (inactive)
language-php, v0.37.3 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.1 (active)
language-ruby, v0.70.2 (active)
language-ruby-on-rails, v0.25.1 (active)
language-sass, v0.57.0 (active)
language-shellscript, v0.23.0 (active)
language-source, v0.9.0 (active)
language-sql, v0.25.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.29.1 (active)
language-toml, v0.18.1 (active)
language-xml, v0.34.12 (active)
language-yaml, v0.27.1 (active)

# Dev
No dev packages
```

**Comment by equake** [comment]
I'm having this same issue.
:(

**Comment by cchase88** [comment]
I'm not too familiar with CoffeeScript, but when looking at the referenced line in the nimble-info.coffee it appears the variable `folderPath` should read `@folderPath` instead.

**Comment by gatmac** [comment]
Thanks cchase88, fixed it for me too... never would have figured that out on my own. Strangely, the nim-atom plugin worked fine on Windows.

**Comment by tro3** [comment]
Same for me as well, but it killed autocomplete.  Single-char change repaired it.

@russpowers - are you still maintaining this repo?

**Comment by Nobabs27** [comment]
I keep getting this error too.

**Comment by rosshadden** [comment]
Same. I just tried the package for the first time, but I get this error and also autocomplete doesn't work.

**Comment by russpowers** [comment]
It should be working properly now, I just published a new version.
