### ISSUE TITLE
Uncaught ReferenceError: options is not defined

### ISSUE THREAD

**Issue by k1tt3hk4t** [russpowers/nim-atom#25]
[Enter steps to reproduce:]

1. ???

**Atom**: 1.19.0-beta0 x64
**Electron**: 1.6.9
**OS**: Ubuntu 16.04.2
**Thrown From**: [nim](https://github.com/russpowers/nim-atom) package 0.3.6

### Stack Trace

Uncaught ReferenceError: options is not defined

```
At /home/david/.atom/packages/nim/lib/compiler.coffee:84

ReferenceError: options is not defined
    at /packages/nim/lib/compiler.coffee:84:57
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom-beta/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at BufferedProcess.handleError (/usr/share/atom-beta/resources/app/src/buffered-process.js:385:26)
    at ChildProcess.<anonymous> (/usr/share/atom-beta/resources/app/src/buffered-process.js:373:22)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -8:30 application:open-folder (div.tool-panel.tree-view)
     -8:18 tree-view:add-file (span.name.icon.icon-file-directory)
 13x -8:15.7.0 core:backspace (input.hidden-input)
     -8:13.8.0 core:confirm (input.hidden-input)
     -8:10.6.0 intentions:highlight (input.hidden-input)
     -8:10.5.0 core:save (input.hidden-input)
     -0:10.2.0 intentions:highlight (input.hidden-input)
     -0:10 core:save (input.hidden-input)
     -0:09.4.0 core:backspace (input.hidden-input)
     -0:08.9.0 intentions:highlight (input.hidden-input)
     -0:08.7.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
build-tools 4.5.9 
busy-signal 1.4.3 
highlight-selected 0.13.1 
intentions 1.1.2 
language-nim 0.2.2 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.6.2 
minimap 4.28.2 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-selection 4.4.0 
nim 0.3.6 
```

**Comment by Sembrani** [comment]
[Enter steps to reproduce:]

1. Open existing Nim Project in Atom from "File -> Reopen Project" That no longer exists / has been moved

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [nim](https://github.com/russpowers/nim-atom) package 0.3.6


### Stack Trace

Uncaught ReferenceError: options is not defined

```
At C:\Users\arowlands\.atom\packages\nim\lib\compiler.coffee:84

ReferenceError: options is not defined
    at /packages/nim/lib/compiler.coffee:84:57
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at BufferedProcess.handleError (~/AppData/Local/atom/app-1.20.1/resources/app/src/buffered-process.js:385:26)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.20.1/resources/app/src/buffered-process.js:373:22)
    at emitOne (events.js:96:13)
    at ChildProcess.emit (events.js:188:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:213:12)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
```

### Non-Core Packages

```
busy-signal 1.4.3 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.10 
nim 0.3.6 
```
