### ISSUE TITLE
Uncaught TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by tmm1** [russpowers/nim-atom#4]
**Atom Version**: 1.0.18
**System**: Mac OS X 10.11
**Thrown From**: [nim](https://github.com/russpowers/nim-atom) package, v0.2.14

### Stack Trace

Uncaught TypeError: Converting circular structure to JSON

```
At /Users/tmm1/.atom/packages/nim/lib/util.coffee:13

TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at module.exports.prettyPrint (/Users/tmm1/.atom/packages/nim/lib/util.coffee:13:10)
    at PersistentCaas.Caas.onCommandFailed (/Users/tmm1/.atom/packages/nim/lib/caas.coffee:36:12)
    at process.BufferedProcess.exit (/Users/tmm1/.atom/packages/nim/lib/persistent-caas.coffee:75:12)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:467:12)
```

### Commands

```
     -0:11.6.0 vim-mode:search-current-word (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 11x -0:11.2.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:10.6.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  7x -0:10.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  4x -0:09.9.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 15x -0:09.6.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  5x -0:08.5.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:08.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:07.8.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:07.2.0 core:save (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 23x -0:06.8.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:04.9.0 vim-mode:delete (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:04.5.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:03.0 vim-mode:put-before (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:02.3.0 vim-mode:move-to-last-character-of-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:02.1.0 vim-mode:insert-after (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "terminal",
      "git-plus",
      "atomatigit",
      "term2",
      "language-nim"
    ],
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "nim": {
    "nimExecutablePath": "/usr/local/bin/nim",
    "nimsuggestEnabled": true,
    "nimsuggestExecutablePath": "~/.nimble/bin/nimsuggest"
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.8.7
autocomplete-emojis, v2.2.2
color-picker, v2.0.12
git, v0.0.0
go-plus, v3.5.1
language-puppet, v0.14.0
language-rust, v0.4.5
linter, v1.6.0
linter-rust, v0.2.9
minimap, v4.13.4
minimap-git-diff, v4.1.8
minimap-hide, v0.3.0
nim, v0.2.14
racer, v0.17.2
remote-atom, v1.2.7
rust-api-docs-helper, v0.5.1
vim-mode, v0.60.0

# Dev
No dev packages
```

**Comment by russpowers** [comment]
Thanks for the report.  This is now fixed in master, but I'm still fixing some issues with build & run before I publish it.
